//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_MitBud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string CompanyUserId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
    }
}
