//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_MitBud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int Id { get; set; }
        public string Company_Id { get; set; }
        public string Client_Id { get; set; }
        public string Message { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
