//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_MitBud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string Client_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> ClientPostCode { get; set; }
        public string ClientAddress { get; set; }
        public string ClientTelephone { get; set; }
        public string ClientEmail { get; set; }
        public string WhoAreYou { get; set; }
        public Nullable<decimal> TaskCost { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
